// =============================================================================
// Product catalog seed -- schema + pricing-match verification
// =============================================================================
// Guards supabase/seed-product-catalog.sql (generated by
// scripts/generate-catalog-seed.ts). The fixture is the REAL output of running
// that seed against a Postgres instance with schema.sql's catalog tables, so
// this asserts against rows the database actually produced, not a hand-written
// approximation of them.
//
// Two things have to hold or the seed is useless:
//   1. Every row parses under the store's own Zod schemas -- otherwise
//      productStore.ts drops the catalog and the price list is empty again.
//   2. Every product identity the pricing engine matches on resolves to
//      exactly one row -- otherwise an order line prices as null.
// =============================================================================
import { describe, it, expect } from "vitest";
import { PanelRowSchema, TrackRowSchema, FixingRowSchema, SealantRowSchema, ColourRowSchema } from "./productMappers";
import seeded from "./__seeded-catalog.fixture.json";

describe("product catalog seed", () => {
  it("seeds every catalog table", () => {
    expect(seeded.panels.length).toBe(3);
    expect(seeded.tracks.length).toBe(9);
    expect(seeded.fixings.length).toBe(2);
    expect(seeded.sealants.length).toBe(2);
    expect(seeded.colours.length).toBe(5);
  });

  it("produces colour rows the store's schema accepts", () => {
    for (const row of seeded.colours) {
      const parsed = ColourRowSchema.safeParse(row);
      expect(parsed.success, `colour ${JSON.stringify(row.code)}: ${!parsed.success ? JSON.stringify(parsed.error.issues) : ""}`).toBe(true);
    }
  });

  it("seeds every stocked colour the estimator offers", () => {
    // Mirrors data.ts's EXT_STOCKED_COLOURS -- the swatch grid reads those
    // codes, so a missing row means a colour with no catalog entry behind it.
    for (const code of ["OW", "GG", "MO", "SL", "AG"]) {
      expect(seeded.colours.filter(c => c.code === code).length, `colour ${code}`).toBe(1);
    }
  });

  it("produces panel rows the store's schema accepts", () => {
    for (const row of seeded.panels) {
      const parsed = PanelRowSchema.safeParse(row);
      expect(parsed.success, `panel ${JSON.stringify(row.label)}: ${!parsed.success ? JSON.stringify(parsed.error.issues) : ""}`).toBe(true);
    }
  });

  it("produces track rows the store's schema accepts", () => {
    for (const row of seeded.tracks) {
      const parsed = TrackRowSchema.safeParse(row);
      expect(parsed.success, `track ${JSON.stringify(row.label)}: ${!parsed.success ? JSON.stringify(parsed.error.issues) : ""}`).toBe(true);
    }
  });

  it("produces fixing and sealant rows the store's schemas accept", () => {
    for (const row of seeded.fixings) {
      const parsed = FixingRowSchema.safeParse(row);
      expect(parsed.success, `fixing ${JSON.stringify(row.code)}: ${!parsed.success ? JSON.stringify(parsed.error.issues) : ""}`).toBe(true);
    }
    for (const row of seeded.sealants) {
      const parsed = SealantRowSchema.safeParse(row);
      expect(parsed.success, `sealant ${JSON.stringify(row.product)}: ${!parsed.success ? JSON.stringify(parsed.error.issues) : ""}`).toBe(true);
    }
  });

  // The identities below mirror priceEstimateReportData.ts's own lookups. If a
  // report line can't find its row here, that line prices as null in a real
  // order.
  it("resolves every panel type the estimator can emit", () => {
    for (const type of [51, 64, 78]) {
      expect(seeded.panels.filter(p => p.type === type).length, `panel type ${type}`).toBe(1);
    }
  });

  it("resolves every track line buildReportData can emit", () => {
    const wanted: { kind: string; system: string; panelType: number | null }[] = [
      { kind: "c-track", system: "internal", panelType: 51 },
      { kind: "c-track", system: "internal", panelType: 64 },
      { kind: "c-track", system: "internal", panelType: 78 },
      { kind: "j-track", system: "internal", panelType: 78 },
      { kind: "head-flash", system: "internal", panelType: null },
      { kind: "c-track", system: "external", panelType: 78 },
      { kind: "j-track", system: "external", panelType: 78 },
      { kind: "z-flash", system: "external", panelType: 78 },
      { kind: "head-flash", system: "external", panelType: null },
    ];
    for (const w of wanted) {
      // Exactly the predicate priceEstimateReportData.ts uses.
      const matches = seeded.tracks.filter(tr =>
        tr.kind === w.kind
        && (tr.system === w.system || tr.system === "both")
        && (w.panelType == null || tr.panel_type == null || tr.panel_type === w.panelType));
      expect(matches.length, `${w.kind}/${w.system}/${w.panelType} matched ${matches.length}`).toBe(1);
    }
  });

  it("resolves both fixing lengths and both sealant systems", () => {
    expect(seeded.fixings.filter(f => f.length_mm === 30).length).toBe(1);
    expect(seeded.fixings.filter(f => f.length_mm === 16).length).toBe(1);
    expect(seeded.sealants.filter(s => s.system === "internal").length).toBe(1);
    expect(seeded.sealants.filter(s => s.system === "external").length).toBe(1);
  });

  it("leaves the deprecated per-item price columns null -- prices come from price lists", () => {
    for (const p of seeded.panels) expect(p.price_per_panel).toBeNull();
    for (const t of seeded.tracks) expect(t.price_per_metre).toBeNull();
  });
});
