// =============================================================================
// Education Hub -- document catalog
// =============================================================================
// Catalog types, mock/real document data, and the full-text search index.
// Mock document catalog for the Education Hub tab. This is UI placeholder
// content (not verified product/spec data like ../data), so it lives here
// rather than in data.ts -- it'll be swapped for a real fetch later.
// =============================================================================
import MiniSearch from "minisearch";
import eduDocumentsRaw from "../eduDocuments.json";
import eduSearchIndexJson from "../eduSearchIndex.json?raw";
import { cx, BLUE, GOLD } from "../styleTokens";

export interface EduSection { name: string; description: string; pages: string; }
export interface EduDocument {
  id: string; title: string; category: string; tags: string[]; description: string;
  edition: string; date: string; fileSize: string; fileType: string; pageCount: number;
  swatch: string; sections: EduSection[];
  // Real documents only -- path under public/, resolved against Vite's BASE_URL so
  // it works both in dev and once deployed under the GitHub Pages subpath. Mock
  // entries with no real PDF yet simply omit this field.
  fileUrl?: string;
}
export const EDU_CATEGORIES = [
  "All", "Technical Guides", "Installation", "Connection Details",
  "Fire & Acoustic", "External Walls", "Estimating", "Compliance",
] as const;
export type EduCategory = typeof EDU_CATEGORIES[number];

// Real documents (with a fileUrl) are catalogued via scripts/add-education-doc.mjs
// into src/eduDocuments.json / src/eduSearchIndex.json rather than hand-authored here --
// see that script for the add/update workflow. swatch is stored in JSON as a colour KEY
// ("blue"/"gold"/"slate"), not a literal value, since JSON can't reference the BLUE/GOLD
// CSS-variable tokens directly; EDU_SWATCH_MAP resolves it below. NAVY is deliberately
// excluded from the rotation -- in dark mode that token is repurposed as the primary-text
// colour (a near-white neutral for legibility), not an actual navy fill, so using it here
// would render a white icon on a near-white block. "#334155" (Tailwind slate-700) is a
// theme-stable neutral used the same way the app already hardcodes slate-700 elsewhere.
export const EDU_SWATCH_MAP: Record<string, string> = { blue: BLUE, gold: GOLD, slate: "#334155" };
export const EDU_DOCUMENTS: EduDocument[] = (eduDocumentsRaw as EduDocument[]).map(d => ({
  ...d,
  swatch: EDU_SWATCH_MAP[d.swatch] ?? d.swatch,
  fileUrl: d.fileUrl ? `${import.meta.env.BASE_URL}${d.fileUrl}` : undefined,
}));

// Full-text search over the catalog, generated by scripts/add-education-doc.mjs from each
// document's extracted PDF text (mock entries with no PDF are indexed on metadata only).
export const eduSearchIndex = MiniSearch.loadJSON(eduSearchIndexJson, {
  idField: "id",
  fields: ["title", "tags", "category", "description", "text"],
  storeFields: ["id"],
});

// Shared "category" badge look -- reuses the app's existing hardcoded info-badge
// convention (see cx.infoNote/cx.infoBox) rather than inventing a new token.
export const eduBadgeCx = cx.badge + " bg-blue-50 dark:bg-blue-950/40 text-blue-700 dark:text-blue-300";
