// =============================================================================
// Education Hub
// =============================================================================
// Self-contained document catalog/viewer page (no dependency on Wall or the
// compute engine) -- catalog types, mock/real document data, full-text search
// index, filter/card/detail-panel UI, the in-app PDF viewer, and the
// EducationHub page component itself. Also owns the pdfjs-dist lazy-loader:
// pdfjs (plus its ~1.3MB worker) is only needed once someone actually opens a
// real PDF here, so it's dynamically imported instead of bundled into the
// main chunk, and the loader promise is cached so the module + worker setup
// only happen once, on first use.
// =============================================================================
import { useState, useMemo, useRef, useEffect } from "react";
import {
  Search, Clock, FileText, Share2, MoreVertical, ChevronRight, ChevronLeft, Maximize2, Minimize2,
} from "lucide-react";
import MiniSearch from "minisearch";
import eduDocumentsRaw from "../eduDocuments.json";
import eduSearchIndexJson from "../eduSearchIndex.json?raw";
import type * as PdfjsLib from "pdfjs-dist";
import { cx, BLUE, GOLD, WHITE, NAVY, MUTED } from "../styleTokens";
import type { EffectiveLayout } from "../useLayoutMode";
import { CardGrid, SectionLabel, Row } from "../ui/primitives";
import { clamp } from "../estimate/mathUtils";

let pdfjsLibPromise: Promise<typeof PdfjsLib> | null = null;
const loadPdfjs = () => {
  if (!pdfjsLibPromise) {
    pdfjsLibPromise = Promise.all([
      import("pdfjs-dist"),
      import("pdfjs-dist/build/pdf.worker.min.mjs?url"),
    ]).then(([lib, worker]) => {
      lib.GlobalWorkerOptions.workerSrc = worker.default;
      return lib;
    });
  }
  return pdfjsLibPromise;
};

// --- Education Hub -------------------------------------------------------------
// Mock document catalog for the Education Hub tab. This is UI placeholder
// content (not verified product/spec data like ./data), so it lives here
// rather than in data.ts -- it'll be swapped for a real fetch later.
export interface EduSection { name: string; description: string; pages: string; }
export interface EduDocument {
  id: string; title: string; category: string; tags: string[]; description: string;
  edition: string; date: string; fileSize: string; fileType: string; pageCount: number;
  swatch: string; sections: EduSection[];
  // Real documents only -- path under public/, resolved against Vite's BASE_URL so
  // it works both in dev and once deployed under the GitHub Pages subpath. Mock
  // entries with no real PDF yet simply omit this field.
  fileUrl?: string;
}
export const EDU_CATEGORIES = [
  "All", "Technical Guides", "Installation", "Connection Details",
  "Fire & Acoustic", "External Walls", "Estimating", "Compliance",
] as const;
export type EduCategory = typeof EDU_CATEGORIES[number];

// Real documents (with a fileUrl) are catalogued via scripts/add-education-doc.mjs
// into src/eduDocuments.json / src/eduSearchIndex.json rather than hand-authored here --
// see that script for the add/update workflow. swatch is stored in JSON as a colour KEY
// ("blue"/"gold"/"slate"), not a literal value, since JSON can't reference the BLUE/GOLD
// CSS-variable tokens directly; EDU_SWATCH_MAP resolves it below. NAVY is deliberately
// excluded from the rotation -- in dark mode that token is repurposed as the primary-text
// colour (a near-white neutral for legibility), not an actual navy fill, so using it here
// would render a white icon on a near-white block. "#334155" (Tailwind slate-700) is a
// theme-stable neutral used the same way the app already hardcodes slate-700 elsewhere.
export const EDU_SWATCH_MAP: Record<string, string> = { blue: BLUE, gold: GOLD, slate: "#334155" };
export const EDU_DOCUMENTS: EduDocument[] = (eduDocumentsRaw as EduDocument[]).map(d => ({
  ...d,
  swatch: EDU_SWATCH_MAP[d.swatch] ?? d.swatch,
  fileUrl: d.fileUrl ? `${import.meta.env.BASE_URL}${d.fileUrl}` : undefined,
}));

// Full-text search over the catalog, generated by scripts/add-education-doc.mjs from each
// document's extracted PDF text (mock entries with no PDF are indexed on metadata only).
export const eduSearchIndex = MiniSearch.loadJSON(eduSearchIndexJson, {
  idField: "id",
  fields: ["title", "tags", "category", "description", "text"],
  storeFields: ["id"],
});

// Shared "category" badge look -- reuses the app's existing hardcoded info-badge
// convention (see cx.infoNote/cx.infoBox) rather than inventing a new token.
export const eduBadgeCx = cx.badge + " bg-blue-50 dark:bg-blue-950/40 text-blue-700 dark:text-blue-300";

export const FilterChips = ({ active, onChange }: { active: EduCategory; onChange: (c: EduCategory) => void }) => (
  <div className="flex flex-wrap gap-2">
    {EDU_CATEGORIES.map(c => {
      const on = active === c;
      return (
        <button key={c} onClick={() => onChange(c)}
          className={"rounded-full border px-3.5 py-1.5 text-xs font-bold transition-all active:scale-95 " + (on ? "" : "border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800")}
          style={on ? { borderColor: BLUE, background: BLUE, color: WHITE } : { color: BLUE }}>
          {c}
        </button>
      );
    })}
  </div>
);

export const RecentlyViewedStrip = ({ ids, docs, onSelect }: { ids: string[]; docs: EduDocument[]; onSelect: (id: string) => void }) => {
  if (ids.length === 0) return null;
  const recentDocs = ids.map(id => docs.find(d => d.id === id)).filter((d): d is EduDocument => !!d);
  return (
    <div className="mt-5">
      <SectionLabel icon={<Clock size={14} />}>Recently Viewed</SectionLabel>
      <div className="flex gap-2 overflow-x-auto pb-1">
        {recentDocs.map(d => (
          <button key={d.id} onClick={() => onSelect(d.id)}
            className="shrink-0 w-56 rounded-xl border-2 border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-3.5 py-3 text-left active:scale-95 transition-all">
            <div className="text-sm font-bold truncate" style={{ color: NAVY }}>{d.title}</div>
            <div className="mt-1 flex items-center justify-between gap-2 text-xs font-medium" style={{ color: MUTED }}>
              <span className="truncate">{d.category} · p.{d.pageCount}</span>
              <ChevronRight size={13} className="shrink-0" style={{ color: BLUE }} />
            </div>
          </button>
        ))}
      </div>
    </div>
  );
};

// Touching anywhere on the card selects the document, updating the persistent detail
// column/panel (see EducationHub) -- the action buttons below route through the same
// callback (with stopPropagation so a button press doesn't double-fire the card's handler).
export const DocumentCard = ({ doc, selected, onSelect, onQuickScan }: { doc: EduDocument; selected: boolean; onSelect: (id: string) => void; onQuickScan: (id: string) => void }) => (
  <div onClick={() => onSelect(doc.id)}
    className={cx.card + " flex cursor-pointer flex-col gap-3"} style={selected ? { borderColor: BLUE, borderWidth: 2 } : undefined}>
    <div className="h-24 rounded-lg grid place-items-center" style={{ background: doc.swatch }}>
      <FileText size={28} color={WHITE} />
    </div>
    <div>
      <span className={eduBadgeCx}>{doc.category}</span>
      <div className="mt-2 text-sm font-bold" style={{ color: NAVY }}>{doc.title}</div>
      <p className="mt-1 text-sm leading-relaxed line-clamp-2" style={{ color: MUTED }}>{doc.description}</p>
    </div>
    <div className="flex flex-wrap gap-1.5">
      {doc.tags.map(t => (
        <span key={t} className="rounded-full bg-slate-100 dark:bg-slate-700 px-2.5 py-0.5 text-xs font-semibold" style={{ color: MUTED }}>{t}</span>
      ))}
    </div>
    <div className={cx.footnote + " pt-0 flex flex-wrap items-center gap-x-1.5 text-xs"}>
      <span>{doc.edition}</span><span>·</span><span>{doc.date}</span><span>·</span><span>{doc.fileSize}</span>
    </div>
    <div className="mt-1 flex items-center gap-2">
      <button onClick={e => { e.stopPropagation(); onQuickScan(doc.id); }}
        className="flex-1 rounded-xl border-2 border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 py-2 text-xs font-bold active:scale-95 transition-all"
        style={{ color: BLUE }}>Quick Scan</button>
      {doc.fileUrl ? (
        <a href={doc.fileUrl} target="_blank" rel="noopener noreferrer" onClick={e => { e.stopPropagation(); onSelect(doc.id); }}
          className="flex-1 rounded-xl py-2 text-center text-xs font-bold active:scale-95 transition-all"
          style={{ background: BLUE, color: WHITE }}>Open PDF</a>
      ) : (
        <button onClick={e => { e.stopPropagation(); onSelect(doc.id); }}
          className="flex-1 rounded-xl py-2 text-xs font-bold active:scale-95 transition-all"
          style={{ background: BLUE, color: WHITE }}>Open PDF</button>
      )}
      {/* No-op overflow button -- a real menu (rename/download/etc) is out of scope for v1. */}
      <button onClick={e => e.stopPropagation()} className="grid h-9 w-9 shrink-0 place-items-center rounded-xl border border-slate-200 dark:border-slate-700 text-slate-400 dark:text-slate-500">
        <MoreVertical size={15} />
      </button>
    </div>
  </div>
);

export const SectionsList = ({ sections, onOpenSection }: { sections: EduSection[]; onOpenSection?: (pages: string) => void }) => (
  <div className="space-y-2.5">
    {sections.map((s, i) => {
      const cardCx = "w-full rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-3.5 py-3 text-left"
        + (onOpenSection ? " active:scale-95 transition-all" : "");
      const body = (
        <>
          <div className="flex items-baseline justify-between gap-2">
            <span className="text-sm font-bold" style={{ color: NAVY }}>{s.name}</span>
            <span className="text-xs font-semibold shrink-0" style={{ color: MUTED }}>p.{s.pages}</span>
          </div>
          <p className="mt-1 text-sm leading-relaxed" style={{ color: MUTED }}>{s.description}</p>
        </>
      );
      // No onOpenSection (no-file doc) -- nothing to jump to, so it's a plain
      // card, not a dead button that looks pressable but does nothing.
      return onOpenSection
        ? <button key={i} onClick={() => onOpenSection(s.pages)} className={cardCx}>{body}</button>
        : <div key={i} className={cardCx}>{body}</div>;
    })}
  </div>
);

export type DetailTab = "scan" | "details" | "related";
export const DETAIL_TABS: { key: DetailTab; label: string }[] = [
  { key: "scan", label: "Quick Scan" }, { key: "details", label: "Details" }, { key: "related", label: "Related" },
];

// Parses the leading page number out of a section's "pages" string ("8-15" -> 8, "37" -> 37) for
// jumping the PDF viewer there.
export const firstPage = (pages: string): number => parseInt(pages, 10) || 1;

// Renders PDF pages ourselves (pdfjs-dist, canvas) with our own Prev/Next controls, rather than
// relying on the browser's native PDF plugin inside an <iframe> -- that approach looked fine on
// desktop Chrome but showed no toolbar/controls at all on mobile/touch browsers, since the full
// PDF.js viewer chrome is a desktop-Chrome-only feature, not a guaranteed <iframe> behavior.
export const PdfViewer = ({ url, page, onPageChange, tall }: { url: string; page: number; onPageChange: (p: number) => void; tall: boolean }) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [pdfDoc, setPdfDoc] = useState<PdfjsLib.PDFDocumentProxy | null>(null);
  const [pageCount, setPageCount] = useState(0);

  useEffect(() => {
    let cancelled = false;
    setPdfDoc(null);
    setPageCount(0);
    loadPdfjs().then(pdfjsLib => pdfjsLib.getDocument({ url }).promise).then(pdf => {
      if (cancelled) return;
      setPdfDoc(pdf);
      setPageCount(pdf.numPages);
    });
    return () => { cancelled = true; };
  }, [url]);

  useEffect(() => {
    if (!pdfDoc || !canvasRef.current) return;
    let cancelled = false;
    const clamped = clamp(page, 1, pdfDoc.numPages);
    pdfDoc.getPage(clamped).then(pdfPage => {
      if (cancelled || !canvasRef.current) return;
      const canvas = canvasRef.current;
      const containerWidth = canvas.parentElement?.clientWidth || 600;
      const unscaled = pdfPage.getViewport({ scale: 1 });
      const viewport = pdfPage.getViewport({ scale: containerWidth / unscaled.width });
      canvas.width = viewport.width;
      canvas.height = viewport.height;
      const ctx = canvas.getContext("2d");
      if (!ctx) return;
      pdfPage.render({ canvasContext: ctx, viewport });
    });
    return () => { cancelled = true; };
  }, [pdfDoc, page, tall]);

  return (
    <div className="mt-1 overflow-hidden rounded-lg border border-slate-200 dark:border-slate-700">
      <div className="flex items-center justify-between gap-2 border-b border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 px-3 py-2">
        <button onClick={() => onPageChange(page - 1)} disabled={page <= 1} title="Previous page"
          className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 dark:text-slate-400 disabled:opacity-30">
          <ChevronLeft size={16} />
        </button>
        <span className="text-xs font-bold" style={{ color: MUTED }}>Page {page} of {pageCount || "-"}</span>
        <button onClick={() => onPageChange(page + 1)} disabled={!pageCount || page >= pageCount} title="Next page"
          className="grid h-8 w-8 place-items-center rounded-lg text-slate-500 dark:text-slate-400 disabled:opacity-30">
          <ChevronRight size={16} />
        </button>
      </div>
      <div className={`overflow-auto bg-slate-100 dark:bg-slate-950 ${tall ? "h-[calc(100vh-200px)]" : "h-[60vh]"}`}>
        <canvas ref={canvasRef} className="mx-auto block" />
      </div>
    </div>
  );
};

export const DocumentDetailPanel = ({ doc, allDocs, tab, onTabChange, onSelectRelated, expanded, onToggleExpand, layoutMode }: {
  doc: EduDocument; allDocs: EduDocument[]; tab: DetailTab; onTabChange: (t: DetailTab) => void;
  onSelectRelated: (id: string) => void;
  expanded: boolean; onToggleExpand: () => void; layoutMode: EffectiveLayout;
}) => {
  const [currentPage, setCurrentPage] = useState(1);
  useEffect(() => setCurrentPage(1), [doc.id]);
  const related = allDocs.filter(d => d.id !== doc.id && d.category === doc.category).slice(0, 4);
  // Maximised on desktop gets room for a side-by-side layout; maximised on phone (or
  // not maximised at all) keeps the PDF viewer and contents stacked in one column.
  const sideBySide = expanded && layoutMode === "web";
  // While side-by-side, the doc info/actions/tabs move into the sticky contents column
  // next to "Sections in this guide" instead of sitting above the two-column grid -- but
  // only for the Quick Scan tab, which is the only one that renders that grid; Details/
  // Related still render single-column with the header on top, same as non-maximised.
  const headerInSidebar = sideBySide && tab === "scan" && !!doc.fileUrl;

  const header = (
    <>
      <div className="mb-3 flex items-center justify-between gap-2">
        <span className="truncate text-xs font-bold uppercase tracking-widest" style={{ color: MUTED }}>Document viewer</span>
        <button onClick={onToggleExpand} title={expanded ? "Exit full screen" : "Full screen"}
          className="grid h-8 w-8 shrink-0 place-items-center rounded-lg border border-slate-200 dark:border-slate-700 text-slate-400 dark:text-slate-500">
          {expanded ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
        </button>
      </div>
      <div className="h-32 rounded-lg grid place-items-center" style={{ background: doc.swatch }}>
        <FileText size={32} color={WHITE} />
      </div>
      <div className="mt-3 text-base font-bold" style={{ color: NAVY }}>{doc.title}</div>
      <span className={eduBadgeCx + " mt-1.5 inline-block"}>{doc.category}</span>
      <div className="mt-3 space-y-1">
        <Row k="Edition" v={doc.edition} dim />
        <Row k="Date" v={doc.date} dim />
        <Row k="File" v={`${doc.fileType} · ${doc.fileSize}`} dim />
      </div>
      <div className="mt-3 flex items-center gap-2">
        {doc.fileUrl ? (
          <a href={doc.fileUrl} target="_blank" rel="noopener noreferrer"
            className="flex-1 rounded-xl py-2.5 text-center text-sm font-bold" style={{ background: BLUE, color: WHITE }}>Open PDF</a>
        ) : (
          <button className="flex-1 rounded-xl py-2.5 text-sm font-bold" style={{ background: BLUE, color: WHITE }}>Open PDF</button>
        )}
        <button className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 dark:border-slate-700 text-slate-400 dark:text-slate-500"><Share2 size={15} /></button>
        <button className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 dark:border-slate-700 text-slate-400 dark:text-slate-500"><MoreVertical size={15} /></button>
      </div>
    </>
  );

  const tabsNav = (
    <div className="mt-4 grid grid-cols-3 gap-1 rounded-xl border border-slate-200 dark:border-slate-700 p-1">
      {DETAIL_TABS.map(t => (
        <button key={t.key} onClick={() => onTabChange(t.key)}
          className={"rounded-lg py-2 text-xs font-bold transition-all " + (tab === t.key ? "" : "text-slate-400 dark:text-slate-500")}
          style={tab === t.key ? { background: BLUE, color: WHITE } : undefined}>
          {t.label}
        </button>
      ))}
    </div>
  );

  return (
    <div className={cx.card}>
      {!headerInSidebar && (
        <>
          {header}
          {tabsNav}
        </>
      )}
      <div className={headerInSidebar ? "" : "mt-4"}>
        {tab === "scan" && (
          doc.fileUrl ? (
            sideBySide ? (
              <div className="grid grid-cols-[1fr_320px] gap-6 items-start">
                <PdfViewer key={doc.id} url={doc.fileUrl} page={currentPage} onPageChange={setCurrentPage} tall={expanded} />
                <div className="sticky top-4 max-h-[calc(100vh-200px)] overflow-y-auto">
                  {header}
                  {tabsNav}
                  <div className={cx.cardHd + " mt-4"}>Sections in this guide</div>
                  <SectionsList sections={doc.sections} onOpenSection={pages => setCurrentPage(firstPage(pages))} />
                </div>
              </div>
            ) : (
              <>
                <PdfViewer key={doc.id} url={doc.fileUrl} page={currentPage} onPageChange={setCurrentPage} tall={expanded} />
                <div className={cx.cardHd + " mt-4"}>Sections in this guide</div>
                <SectionsList sections={doc.sections} onOpenSection={pages => setCurrentPage(firstPage(pages))} />
              </>
            )
          ) : (
            <>
              <div className={cx.cardHd}>About this guide</div>
              <p className="text-sm leading-relaxed" style={{ color: MUTED }}>{doc.description}</p>
              <div className={cx.cardHd + " mt-4"}>Sections in this guide</div>
              <SectionsList sections={doc.sections} />
            </>
          )
        )}
        {tab === "details" && (
          <div className="space-y-1">
            <Row k="Pages" v={doc.pageCount} dim />
            <Row k="Tags" v={doc.tags.join(", ")} dim />
            <Row k="Category" v={doc.category} dim />
          </div>
        )}
        {tab === "related" && (
          related.length === 0
            ? <p className={cx.footnote}>No related documents in this category.</p>
            : <div className="space-y-2">
                {related.map(d => (
                  <button key={d.id} onClick={() => onSelectRelated(d.id)}
                    className="w-full rounded-xl border border-slate-200 dark:border-slate-700 px-3.5 py-2.5 text-left text-sm font-semibold" style={{ color: NAVY }}>
                    {d.title}
                  </button>
                ))}
              </div>
        )}
      </div>
    </div>
  );
};

export const EducationHub = ({ layoutMode }: { layoutMode: EffectiveLayout }) => {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<EduCategory>("All");
  const [selectedId, setSelectedId] = useState<string>(EDU_DOCUMENTS[0].id);
  const [recentIds, setRecentIds] = useState<string[]>([]);
  const [detailTab, setDetailTab] = useState<DetailTab>("scan");
  // Grid + a persistent detail panel (aside on web, stacked below on phone) is always the
  // default view -- expanded is purely an opt-in "make the viewer bigger" toggle, not a
  // separate mode the user has to enter/exit to see anything.
  const [expanded, setExpanded] = useState(false);

  const filtered = useMemo(() => {
    const q = query.trim();
    const byCategory = (d: EduDocument) => category === "All" || d.category === category;
    if (!q) return EDU_DOCUMENTS.filter(byCategory);
    // Full-text search (title/tags/category/description/extracted PDF text) via the
    // pre-built MiniSearch index -- see scripts/add-education-doc.mjs.
    const matchIds = new Set(eduSearchIndex.search(q, { prefix: true, fuzzy: 0.2, boost: { title: 3, tags: 2 } }).map(r => r.id));
    return EDU_DOCUMENTS.filter(d => byCategory(d) && matchIds.has(d.id));
  }, [query, category]);

  const selectDoc = (id: string) => {
    setSelectedId(id);
    setRecentIds(prev => [id, ...prev.filter(x => x !== id)].slice(0, 6));
    setDetailTab("scan"); // every selection path lands on the Quick Scan view.
  };

  const openQuickScan = (id: string) => {
    selectDoc(id);
    setExpanded(true);
  };

  const selectedDoc = EDU_DOCUMENTS.find(d => d.id === selectedId) ?? EDU_DOCUMENTS[0];

  const gridBody = (
    <>
      <div className="mt-4 flex items-center gap-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-4 py-3 shadow-sm">
        <Search size={16} className="shrink-0" style={{ color: MUTED }} />
        <input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search guides, tags, categories..."
          className="w-full bg-transparent text-sm outline-none" style={{ color: NAVY }} />
      </div>
      <div className="mt-3"><FilterChips active={category} onChange={setCategory} /></div>
      <RecentlyViewedStrip ids={recentIds} docs={EDU_DOCUMENTS} onSelect={selectDoc} />
      <div className="mt-5"><SectionLabel icon={<FileText size={14} />}>All Documents ({filtered.length})</SectionLabel></div>
      {filtered.length === 0 ? (
        <div className={cx.card + " mt-3 text-center"}>
          <p className={cx.footnote}>No documents match your search.</p>
        </div>
      ) : (
        <CardGrid layoutMode={layoutMode} minWidth={280}>
          {filtered.map(d => (
            <DocumentCard key={d.id} doc={d} selected={d.id === selectedId} onSelect={selectDoc} onQuickScan={openQuickScan} />
          ))}
        </CardGrid>
      )}
    </>
  );

  const detailPanel = (
    <DocumentDetailPanel
      doc={selectedDoc} allDocs={EDU_DOCUMENTS} tab={detailTab} onTabChange={setDetailTab} onSelectRelated={selectDoc}
      expanded={expanded} onToggleExpand={() => setExpanded(v => !v)} layoutMode={layoutMode}
    />
  );

  // The wrapper around detailPanel keeps the same element/position across the expanded
  // toggle -- only its className changes -- so React preserves DocumentDetailPanel's (and
  // PdfViewer's) component state (current page, loaded PDF) instead of remounting it and
  // losing all of that whenever full screen is toggled on/off.
  const expandedClass = "fixed inset-0 z-50 overflow-y-auto bg-slate-50 p-4 dark:bg-slate-950 md:p-8";

  if (layoutMode === "phone") {
    return (
      <div className="mt-2">
        {gridBody}
        <div className={expanded ? expandedClass : "mt-6"}>{detailPanel}</div>
      </div>
    );
  }

  return (
    <div className="mt-2 grid grid-cols-[1fr_380px] items-start gap-6">
      <div className="min-w-0">{gridBody}</div>
      <aside className={expanded ? expandedClass : "sticky top-5"}>{detailPanel}</aside>
    </div>
  );
};
